import functools
import typing
import string
import random
import pytest

def nwords(s: str) -> int:
    """
    Determines the amount of words in this string.
    """
    word_count = 1
    for c in s:
        if c in string.whitespace:
            word_count += 1
    return word_count
def word_count_iter(it: iter) -> tuple:
    """
    Returns the amount of strings, total words and total characters
    generated by an iterator.
    """
    rows = 0
    words = 0
    characters = 0
    for s in it:
        rows += 1
        words += nwords(s)
        characters += len(s)
    print (rows, words, characters)
